--- drivers/media/dvb-frontends/Makefile	2018-01-28 22:20:33.000000000 +0100
+++ drivers/media/dvb-frontends/Makefile	2018-02-26 20:45:13.000000000 +0100
@@ -1,3 +1,10 @@
+## Added for tbs6680 driver:
+genbin:
+	echo X > tbs6680fe_driver.o_shipped
+
+obj-$(CONFIG_DVB_TBS6680FE) += tbs6680fe.o
+tbs6680fe-objs += kmem_wrap.o tbs6680fe_driver.o
+
 # SPDX-License-Identifier: GPL-2.0
 #
 # Makefile for the kernel DVB frontend device drivers.
